apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: increase-header-size-mesh-wide
  namespace: istio-system
spec:
  configPatches:
  - applyTo: CLUSTER
    match:
      context: SIDECAR_INBOUND
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
          common_http_protocol_options:
            max_request_headers_kb: 16384  # Set the header size limit to 16MB

  - applyTo: CLUSTER
    match:
      context: SIDECAR_OUTBOUND
    patch:
      operation: MERGE
      value:
        typed_config:
          '@type': type.googleapis.com/envoy.config.cluster.v3.Cluster
          common_http_protocol_options:
            max_request_headers_kb: 16384  # Set the header size limit to 16MB

